imports:
    - php
before_commands:
    - "composer install --dev --prefer-source --no-interaction"
filter:
    excluded_paths: [vendor/*, tests/*]
tools:
    php_code_coverage:
        test_command: phpunit -c tests/
    php_code_sniffer:
        config:
            standard: PSR2
    php_cpd: true
    php_hhvm: true
    php_mess_detector: true
    php_pdepend: true
